# Generated by Django 3.2.7 on 2024-06-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedicalanalays',
            name='date',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
