# Generated by Django 3.2.7 on 2024-06-20 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_usermedicalanalays_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermedicalanalays',
            name='date',
        ),
    ]
