# Generated by Django 3.2.7 on 2024-06-28 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_usermedicalanalays_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordscenter',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsclinic',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userrecordshospital',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='UserRecordsHospitalMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.userrecordsclinic')),
            ],
        ),
        migrations.CreateModel(
            name='UserRecordsClinicMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.userrecordsclinic')),
            ],
        ),
        migrations.CreateModel(
            name='UserRecordsCenterMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.userrecordsclinic')),
            ],
        ),
    ]
