# Generated by Django 3.2.7 on 2024-06-28 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20240628_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecordscentermedicine',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.userrecordscenter'),
        ),
        migrations.AlterField(
            model_name='userrecordshospitalmedicine',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.userrecordshospital'),
        ),
    ]
